[0m23:18:23.258562 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017A709F01A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017A71AA7D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017A71AA79D0>]}


============================== 23:18:23.264577 | cbee750e-1745-4965-8d66-522c93eef6b0 ==============================
[0m23:18:23.264577 [info ] [MainThread]: Running with dbt=1.10.4
[0m23:18:23.266159 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\analy\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init netflix', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:18:23.301629 [info ] [MainThread]: Creating dbt configuration folder at C:\Users\analy\.dbt
[0m23:18:23.305531 [debug] [MainThread]: Starter project path: C:\Users\analy\OneDrive\Desktop\NETFLIXDBT\venv\Lib\site-packages\dbt\include\starter_project
[0m23:18:23.353101 [info ] [MainThread]: 
Your new dbt project "netflix" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m23:18:23.354273 [info ] [MainThread]: Setting up your profile.
[0m23:23:19.924009 [info ] [MainThread]: Profile netflix written to C:\Users\analy\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m23:23:19.930274 [debug] [MainThread]: Command `dbt init` succeeded at 23:23:19.929410 after 296.97 seconds
[0m23:23:19.931357 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017A736E9BA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017A73708710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017A73633570>]}
[0m23:23:19.932708 [debug] [MainThread]: Flushing usage events
[0m23:23:21.511651 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:04:02.604821 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2A9CB01A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2AAD6BD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2AAD6B9D0>]}


============================== 00:04:02.608912 | 1604c0e1-81e1-4bde-8787-ef584410db91 ==============================
[0m00:04:02.608912 [info ] [MainThread]: Running with dbt=1.10.4
[0m00:04:02.609623 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\analy\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:04:02.610100 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\analy\OneDrive\Desktop\NETFLIXDBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:04:02.610935 [debug] [MainThread]: Command `dbt run` failed at 00:04:02.610836 after 0.26 seconds
[0m00:04:02.611197 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2AAC4B490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2AAC62E70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2AADD8160>]}
[0m00:04:02.611469 [debug] [MainThread]: Flushing usage events
[0m00:04:03.769036 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:12:19.939158 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232622F01A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232633A7D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232633A79D0>]}


============================== 00:12:19.942770 | ac37b021-c1d2-428a-85c8-2573457a5029 ==============================
[0m00:12:19.942770 [info ] [MainThread]: Running with dbt=1.10.4
[0m00:12:19.943344 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\analy\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:12:19.943743 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\analy\OneDrive\Desktop\NETFLIXDBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:12:19.944622 [debug] [MainThread]: Command `dbt run` failed at 00:12:19.944497 after 0.24 seconds
[0m00:12:19.944898 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002326328F490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232632A2E70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232643E8160>]}
[0m00:12:19.945195 [debug] [MainThread]: Flushing usage events
[0m00:12:21.014271 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:12:33.343481 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6B9801A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6CA3BD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6CA3B9D0>]}


============================== 00:12:33.349684 | aa3400cb-b2e2-42f0-8dca-bba9efa978b9 ==============================
[0m00:12:33.349684 [info ] [MainThread]: Running with dbt=1.10.4
[0m00:12:33.350652 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\analy\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m00:12:33.386276 [info ] [MainThread]: dbt version: 1.10.4
[0m00:12:33.386894 [info ] [MainThread]: python version: 3.13.3
[0m00:12:33.387316 [info ] [MainThread]: python path: C:\Users\analy\OneDrive\Desktop\NETFLIXDBT\venv\Scripts\python.exe
[0m00:12:33.387680 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m00:12:33.816262 [info ] [MainThread]: Using profiles dir at C:\Users\analy\.dbt
[0m00:12:33.817304 [info ] [MainThread]: Using profiles.yml file at C:\Users\analy\.dbt\profiles.yml
[0m00:12:33.817984 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\analy\OneDrive\Desktop\NETFLIXDBT\dbt_project.yml
[0m00:12:33.819191 [info ] [MainThread]: adapter type: snowflake
[0m00:12:33.819738 [info ] [MainThread]: adapter version: 1.9.0
[0m00:12:33.820274 [info ] [MainThread]: Configuration:
[0m00:12:33.820701 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m00:12:33.821137 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m00:12:33.821532 [info ] [MainThread]: Required dependencies:
[0m00:12:33.821968 [debug] [MainThread]: Executing "git --help"
[0m00:12:33.867304 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m00:12:33.867717 [debug] [MainThread]: STDERR: "b''"
[0m00:12:33.868044 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m00:12:33.868408 [info ] [MainThread]: Connection:
[0m00:12:33.868703 [info ] [MainThread]:   account: TDPALWP-SE04961
[0m00:12:33.869021 [info ] [MainThread]:   user: dbt
[0m00:12:33.869299 [info ] [MainThread]:   database: MOVIELENS
[0m00:12:33.869543 [info ] [MainThread]:   warehouse: COMPUTE_WH
[0m00:12:33.869776 [info ] [MainThread]:   role: ACCOUNTADMIN
[0m00:12:33.870021 [info ] [MainThread]:   schema: RAW
[0m00:12:33.870248 [info ] [MainThread]:   authenticator: None
[0m00:12:33.870568 [info ] [MainThread]:   oauth_client_id: None
[0m00:12:33.871174 [info ] [MainThread]:   query_tag: None
[0m00:12:33.871838 [info ] [MainThread]:   client_session_keep_alive: False
[0m00:12:33.872364 [info ] [MainThread]:   host: None
[0m00:12:33.872739 [info ] [MainThread]:   port: None
[0m00:12:33.873092 [info ] [MainThread]:   proxy_host: None
[0m00:12:33.873396 [info ] [MainThread]:   proxy_port: None
[0m00:12:33.873648 [info ] [MainThread]:   protocol: None
[0m00:12:33.873874 [info ] [MainThread]:   connect_retries: 1
[0m00:12:33.874095 [info ] [MainThread]:   connect_timeout: None
[0m00:12:33.874316 [info ] [MainThread]:   retry_on_database_errors: False
[0m00:12:33.874535 [info ] [MainThread]:   retry_all: False
[0m00:12:33.874749 [info ] [MainThread]:   insecure_mode: False
[0m00:12:33.874961 [info ] [MainThread]:   reuse_connections: True
[0m00:12:33.875453 [info ] [MainThread]: Registered adapter: snowflake=1.9.0
[0m00:12:34.121392 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m00:12:34.169759 [debug] [MainThread]: Using snowflake connection "debug"
[0m00:12:34.170122 [debug] [MainThread]: On debug: select 1 as id
[0m00:12:34.170374 [debug] [MainThread]: Opening a new connection, currently in state init
[0m00:12:34.781567 [debug] [MainThread]: Snowflake adapter: Error running SQL: select 1 as id
[0m00:12:34.782255 [debug] [MainThread]: Snowflake adapter: Rolling back transaction.
[0m00:12:34.782597 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m00:12:34.783556 [info ] [MainThread]: [31m2 checks failed:[0m
[0m00:12:34.784278 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\analy\OneDrive\Desktop\NETFLIXDBT\dbt_project.yml> not found

[0m00:12:34.784796 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  250001 (08001): Failed to connect to DB: TDPALWP-SE04961.snowflakecomputing.com:443. Role 'ACCOUNTADMIN' specified in the connect string is not granted to this user. Contact your local system administrator, or attempt to login with another role, e.g. PUBLIC.

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m00:12:34.785992 [debug] [MainThread]: Command `dbt debug` failed at 00:12:34.785884 after 1.57 seconds
[0m00:12:34.786244 [debug] [MainThread]: Connection 'debug' was left open.
[0m00:12:34.786458 [debug] [MainThread]: On debug: No close available on handle
[0m00:12:34.786704 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6E999BA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6EF43890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6E6B0380>]}
[0m00:12:34.787025 [debug] [MainThread]: Flushing usage events
[0m00:12:35.786036 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:47:11.685306 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C90A3901A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C90B44BD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C90B44B9D0>]}


============================== 15:47:11.693204 | 96b251e8-05ca-44fc-8d1b-2b73988681dd ==============================
[0m15:47:11.693204 [info ] [MainThread]: Running with dbt=1.10.4
[0m15:47:11.693957 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\analy\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m15:47:11.694417 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\analy\OneDrive\Desktop\NETFLIXDBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:47:11.695328 [debug] [MainThread]: Command `dbt run` failed at 15:47:11.695205 after 0.32 seconds
[0m15:47:11.695614 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C90B32F490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C90B342E70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C90B4B8160>]}
[0m15:47:11.695895 [debug] [MainThread]: Flushing usage events
[0m15:47:12.780205 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:48:03.564524 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017A30AB01A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017A31B67D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017A31B679D0>]}


============================== 15:48:03.568480 | 54b02e04-ffc3-44b4-b46e-8b9f8a9c9f6a ==============================
[0m15:48:03.568480 [info ] [MainThread]: Running with dbt=1.10.4
[0m15:48:03.569258 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\analy\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:48:03.569764 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\analy\OneDrive\Desktop\NETFLIXDBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:48:03.570624 [debug] [MainThread]: Command `dbt run` failed at 15:48:03.570513 after 0.12 seconds
[0m15:48:03.570985 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017A31A53490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017A31A66E70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017A31BD4160>]}
[0m15:48:03.571421 [debug] [MainThread]: Flushing usage events
[0m15:48:04.864797 [debug] [MainThread]: An error was encountered while trying to flush usage events
